on:
  schedule:
    - cron:  '0 0 * * *'
  push:

name: Daily Update

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Install whois
        run: sudo apt-get install whois

      - name: Generate file
        run: sh asn-blacklist.sh

      - name: Build project
        run: |
          zip --junk-paths release ips_v4.txt ips_v6.txt

      - name: Download latest release
        run: |
          wget -O latest.zip "https://github.com/StephaneBour/ips-from-asn/releases/latest/download/release.zip"
          unzip latest.zip -d latest

      - name: Compare files
        id: compare
        run: |
          if cmp -s "ips_v4.txt" "latest/ips_v4.txt" && cmp -s "ips_v6.txt" "latest/ips_v6.txt"
          then
            exit 2
          fi

      - name: 'Get all tags'
        run: |
          git fetch --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@master"
        with:
          version: ${{ steps.previoustag.outputs.tag }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          release_name: Release ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
